#!/bin/bash
#
# deploy the labnotebook

# stash untracked files
if jekyll build
  then echo Jekyll Generation successful
  else exit $?
fi

if chmod -R 755 _site/*
  then echo chmod successful
  else exit $?
fi

if rsync -aruz _site/* riverdance.cse.ucsc.edu:public_html/
  then echo rsync operation successful
  else exit $?
fi

exit $?
