#!/bin/bash
#
# deploy the labnotebook

# stash untracked files
if jekyll build
  then echo Jekyll Generation successful
  else exit $?
fi

if chmod -R 755 _site/*
  then echo chmod successful
  else exit $?
fi

#if rsync --itemize-changes -anv _site/* riverdance.cse.ucsc.edu:public_html/ > foo
if rsync -av _site/* riverdance.cse.ucsc.edu:public_html/
  then echo rsync operation successful
  else exit $?
fi

exit $?
